### ISSUE TITLE
ListGroup Doc broken

### ISSUE THREAD

**Issue by dynamic11** [dynamic11/wet-react#76]
Please see screenshot for `ListGroup` doc

![Screen Shot 2022-03-09 at 2 18 29 PM](https://user-images.githubusercontent.com/11470442/157515720-da1dd9b1-2b51-4143-b32e-423e2fa0760b.png)

**Comment by alphaoreo** [comment]
I have found and fixed the problem so I will be opening a new pull request with the fixes.
